# An example for creating a Ubuntu container and install python
- name: Create k3s cluster containers
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Create k3s cluster
      community.general.lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams # if you get a 404, try setting protocol: simplestreams
          alias: focal
        profiles: ["k3s"]
        wait_for_ipv4_addresses: true
        timeout: 600
      loop:
        - master
        - node1
        - node2

- name: Prepare k3s cluster containers
  hosts: k3sCluster
  connection: lxd
  gather_facts: false
  tasks:

    - name: Copy kmsg.conf
      copy:
        src: files/kmsg.conf
        dest: /etc/tmpfiles.d/kmsg.conf

    - name: Make /dev/kmsg link
      raw: /usr/bin/systemd-tmpfiles --create

- name: Install k3s on master containers
  hosts: master
  connection: lxd
  gather_facts: false
  tasks:

    - name: Install k3s
      raw: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest INSTALL_K3S_SKIP_START=true sh -s - --snapshotter=native

    - name: Wait till k3s.service file exists
      wait_for:
        path: /etc/systemd/system/k3s.service

    - name: Edit k3s.service file
      lineinfile:
        path: /etc/systemd/system/k3s.service
        state: absent
        regexp: '^ExecStartPre='

    - name: Reload Systemd
      raw: systemctl daemon-reload

    - name: Start k3s
      systemd:
        state: started
        name: k3s

    - name: Check k3s server start up is completed
      raw: /usr/local/bin/kubectl get all --all-namespaces
      register: result
      until: result.stdout.find("ContainerCreating") == -1 and result.stdout.find("Running") != -1
      retries: 10
      delay: 10

- name: Install k3s on worker containers
  hosts: nodes
  connection: lxd
  tasks:

    - name: Gather facts
      delegate_to: master
      setup:

    - name: Set IP Fact
      set_fact:
        master_ip: "{{ ansible_default_ipv4.address }}"

    - name: Get Token
      delegate_to: master
      raw: cat /var/lib/rancher/k3s/server/node-token
      register: result

    - name: Set Token Fact
      set_fact:
        token: "{{ result.stdout_lines[0] }}"

    - name: debug
      debug:
        msg: "IP: {{ master_ip }} Token: {{ token }}"

    - name: Install k3s
      raw: "curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ token }} INSTALL_K3S_SKIP_START=true sh -s - --snapshotter=native"

    - name: Wait till k3s-agent.service file exists
      wait_for:
        path: /etc/systemd/system/k3s-agent.service

    - name: Edit k3s-agent.service file
      lineinfile:
        path: /etc/systemd/system/k3s-agent.service
        state: absent
        regexp: '^ExecStartPre='

    - name: Reload Systemd
      raw: systemctl daemon-reload

    - name: Start k3s-agent
      systemd:
        state: started
        name: k3s-agent

- name: Set label for worker
  hosts: master
  connection: lxd
  gather_facts: false
  tasks:

    - name: Check if nodes has registered
      raw: /usr/local/bin/kubectl get nodes
      register: result
      until: result.stdout.find('node1') != -1 and result.stdout.find('node2') != -1

    - name: debug
      debug:
        msg: "{{ result.stdout_lines }}"

    - name: Label the nodes to worker
      raw: /usr/local/bin/kubectl label node {{ item }} node-role.kubernetes.io/worker=worker-lable
      loop:
        - node1
        - node2

    - name: Display get nodes
      raw: /usr/local/bin/kubectl get nodes
      register: result

    - name: debug
      debug:
        msg: "{{ result.stdout_lines }}"
