# An example for creating a profile
- hosts: localhost
  connection: local
  tasks:
    - name: Create a k3s profile
      community.general.lxd_profile:
        name: k3s
        state: present
        config:
          linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
          raw.lxc: |-
            lxc.apparmor.profile=unconfined
            lxc.cap.drop=
            lxc.cgroup.devices.allow=a
            lxc.mount.auto=proc:rw sys:rw cgroup:rw
            lxc.seccomp.profile=
          security.nesting: "true"
          security.privileged: "true"
          user.user-data: |
            #cloud-config
            apt:
              preserve_sources_list: false
              primary:
                - arches:
                  - amd64
                  uri: "http://archive.ubuntu.com/ubuntu/"
              security:
                - arches:
                  - amd64
                  uri: "http://security.ubuntu.com/ubuntu"
            packages:
              - apt-transport-https
              - ca-certificates
              - curl
              - jq
            package_update: false
            package_upgrade: false
            package_reboot_if_required: false
            locale: en_SG.UTF-8
            locale_configfile: /etc/default/locale
            timezone: Asia/Singapore
            write_files:
            - content: |
                [Unit]
                Description=Mount Make Rshare
                [Service]
                ExecStart=/bin/mount --make-rshare /
                [Install]
                WantedBy=multi-user.target
              owner: root:root
              path: /etc/systemd/system/mount-make-rshare.service
              permissions: '0644'
            runcmd:
              - apt-get -y purge nano
              - apt-get -y autoremove
              - systemctl enable mount-make-rshare
        description: k3s profile for creating k3s container
        devices:
          _dev_sda1:
            path: /dev/sda1
            source: /dev/sda1
            type: unix-block
          aadisable:
            path: /sys/module/nf_conntrack/parameters/hashsize
            source: /dev/null
            type: disk
          aadisable1:
            path: /sys/module/apparmor/parameters/enabled
            source: /dev/null
            type: disk
          boot_dir:
            path: /boot
            source: /boot
            type: disk
          dev_kmsg:
            path: /dev/kmsg
            source: /dev/kmsg
            type: unix-char
          eth0:
            name: eth0
            nictype: bridged
            parent: lxdbr0
            type: nic
          root:
            path: /
            pool: default
            type: disk
