# An example for creating a Ubuntu container and install python
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Delete k3s single
      community.general.lxd_container:
        name: "{{ item }}"
        state: absent
        timeout: 600
      loop:
        - worker2
        - worker1
        - primary
